version: "3.8"
services:
  nqmvul:
    build: .
    volumes:
      - .:/usr/src/app
      - ./reports:/usr/src/app/reports
    depends_on:
      - syft
      - grype
      - ccscanner
      - binwalk
    networks:
      - tooling-net

  syft:
    image: anchore/syft
    networks:
      - tooling-net

  grype:
    image: anchore/grype
    networks:
      - tooling-net

  ccscanner:
    image: ionutnqm/depscanner:latest
    networks:
      - tooling-net
  
  binwalk:
    image: ionutnqm/binwalk_v4:latest
    networks:
      -tooling-net

networks:
  tooling-net:
    driver: bridge
