jobs:
  lint-and-check:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci --ignore-scripts
        
      - name: Run lint
        run: npm run lint

      - name: Check for uncommitted/unignored files
        shell: bash
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes detected"
          else
            echo "error::Detected uncommitted files after running lint."
            git status --verbose --verbose
            exit 1
          fi
